name: ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: run setup
        run: make setup
      - name: run test
        run: make test
      - name: run lint
        run: make lint
